genomes_path: config/genomes.parquet

validation_chroms:
  - NC_000019.10  # human chr19
#   - NC_000085.7  # mouse chr19
#   - NC_052550.1  # chicken chr19
#   - NC_007130.7  # zebrafish chr19
#   - NT_033778.4  # drosophila chr2R
#   - NC_003281.10  # c elegans chrIII

shuffle_seed: 42

n_shards: 64

add_rc: true

intervals:
  # promoters from protein-coding transcripts, similar to gpn-animal-promoter-dataset
  # 256 bp upstream and 256 bp downstream of the TSS
  # the 512/256 here refers to from those regions how to create windows
  # take windows of 512 bp with 256 bp overlap
  # which in this case would typically result in 1 window per promoter
  - v1/512/256

genome_sets:
  - name: animals
    rank_key: kingdom
    rank_value: Metazoa
  - name: vertebrates
    rank_key: phylum
    rank_value: Chordata
  - name: mammals
    rank_key: class
    rank_value: Mammalia
  - name: primates
    rank_key: order
    rank_value: Primates
  - name: humans
    rank_key: species
    rank_value: "Homo sapiens"

output_hf_prefix: gonzalobenegas/genomes-v2
