datasets:
  - traitgym_mendelian
  - traitgym_complex
  - clinvar_missense
  - gnomad_pls_v1
  - gnomad_pls_v2

# HuggingFace repository prefix for dataset uploads
output_hf_prefix: gonzalobenegas/bolinas_evals
